#' Coverage track visualization in the specified genome region
#' 
#' @description
#' Generate coverage track plot in the specified genome region.
#' 
#' @param coverage_table Genome coverage table generated by `load_BigWig`.
#' @param region Genome region used to generate the coverage track plot, must be a GRanges object.
#' @param up_extend How many base pairs to extend upstream the region?
#' @param down_extend How many base pairs to extend downstream the region?
#' @param style Plot style provided by package, check the [document](https://github.com/yimingsun12138/TrackPlotR) for details.
#' @param y_lim The numerical y-axis limit for coverage track plot.
#' @param sample_order The sample order when generating the coverage track.
#' @param col_pal A custom palette used to override coloring for samples.
#' 
#' @return A ggplot object.
#' 
#' @export
coverage_vis_region <- function(coverage_table,
                                region,
                                up_extend = 0,
                                down_extend = 0,
                                style = c('style_1'),
                                y_lim = NULL,
                                sample_order = NULL,
                                col_pal = NULL){
  
  #check parameter
  if(base::class(coverage_table) != 'data.frame'){
    base::stop('coverage_table must be a data.frame object!')
  }
  
  if(!base::all(c('seqnames','start','end','score','Sample') %in% base::colnames(coverage_table))){
    base::stop('missing columns in coverage_table!')
  }
  
  if(base::class(region) != 'GRanges'){
    base::stop('region must be a GRanges object!')
  }else{
    if(base::length(region) != 1){
      base::stop('only 1 region required!')
    }
  }
  
  #extend region
  IRanges::start(region) <- IRanges::start(region) - up_extend
  IRanges::end(region) <- IRanges::end(region) + down_extend
  
  #check style
  style <- style[1]
  if(!(style %in% c('style_1'))){
    base::stop('invalid style!')
  }
  
  #basic plot
  coverage_plot <- coverage_vis_basic(coverage_table = coverage_table,
                                      region = region,
                                      y_lim = y_lim,
                                      sample_order = sample_order,
                                      col_pal = col_pal)
  
  #style
  if(style == 'style_1'){
    coverage_plot <- coverage_plot
  }
  
  #return
  return(coverage_plot)
}

#' Coverage track visualization around specified gene region
#' 
#' @description
#' Generate coverage track plot around specified gene region.
#' 
#' @param coverage_table Genome coverage table generated by `load_BigWig`.
#' @param gene_anno Gene annotation (GTF) file path or a GRanges object which stores the gene annotation information. Ensembl GTF file is recommended.
#' @param column_name Which column in gene_anno stores the gene name to be plotted?
#' @param gene The name of the gene to be plotted.
#' @param up_extend How many base pairs to extend upstream the gene?
#' @param down_extend How many base pairs to extend downstream the gene?
#' @param style Plot style provided by package, check the [document](https://github.com/yimingsun12138/TrackPlotR) for details.
#' @param y_lim The numerical y-axis limit for coverage track plot.
#' @param sample_order The sample order when generating the coverage track.
#' @param col_pal A custom palette used to override coloring for samples.
#' 
#' @return A ggplot object.
#' 
#' @export
coverage_vis_gene <- function(coverage_table,
                              gene_anno,
                              column_name,
                              gene,
                              up_extend = 3000,
                              down_extend = 3000,
                              style = c('style_1'),
                              y_lim = NULL,
                              sample_order = NULL,
                              col_pal = NULL){
  
  #check parameter
  if(base::class(coverage_table) != 'data.frame'){
    base::stop('coverage_table must be a data.frame object!')
  }
  
  if(!base::all(c('seqnames','start','end','score','Sample') %in% base::colnames(coverage_table))){
    base::stop('missing columns in coverage_table!')
  }
  
  if(base::class(gene_anno) != 'GRanges'){
    gene_anno <- rtracklayer::import(con = gene_anno,format = 'gtf')
  }
  
  if(!base::all(c('type',column_name) %in% base::colnames(gene_anno@elementMetadata))){
    base::stop(base::paste0('gene_anno must contain two columns: type and ',column_name,'!'))
  }
  
  #check style
  style <- style[1]
  if(!(style %in% c('style_1'))){
    base::stop('invalid style!')
  }
  
  #get gene region
  idx <- base::which((gene_anno$type == 'gene') & (gene_anno@elementMetadata[,column_name] == gene))
  if(base::length(idx) == 0){
    base::stop(base::paste(gene,'not found in the annotation!',sep = ' '))
  }
  if(base::length(idx) > 1){
    base::stop('multiple gene regions detected in the annotation!')
  }
  
  region <- gene_anno[idx]
  if(region@strand == '-'){
    IRanges::start(region) <- IRanges::start(region) - down_extend
    IRanges::end(region) <- IRanges::end(region) + up_extend
  }else{
    IRanges::start(region) <- IRanges::start(region) - up_extend
    IRanges::end(region) <- IRanges::end(region) + down_extend
  }
  
  #basic plot
  coverage_plot <- coverage_vis_basic(coverage_table = coverage_table,
                                      region = region,
                                      y_lim = y_lim,
                                      sample_order = sample_order,
                                      col_pal = col_pal)
  
  #style
  if(style == 'style_1'){
    coverage_plot <- coverage_plot
  }
  
  #return
  return(coverage_plot)
}